#!/usr/bin/python
import cgi, os, sys
import commands
#import cgitb
#import urllib
#cgitb.enable()
import numpy as np
#import sqlite3
#from decimal import Decimal

kbstopnodes = commands.getoutput('kubectl top nodes')
arenatopnodes = commands.getoutput('arena top node')

gpuusage = arenatopnodes.split('\n')[-2:]

cpuusage = []
memoryusage =  []
for line in kbstopnodes.split('\n')[1:-4]:
    items = line.split()
    c = items[2]
    m = items[4]
    cpuusage.append(float(c[:-1]))
    memoryusage.append(float(m[:-1]))

kbstopnodes = kbstopnodes.replace('\n', '<br>')
arenatopnodes = arenatopnodes.replace('\n', '<br>')


print "Content-Type: text/html\n"
print "<html>"
print "<title>GuiAn G30 cluster monitor</title>"
print "<meta http-equiv='refresh' content='30'>"
print "<h2> The node usage display </h2>"

print '<h3>'
print '<br>'
print ' '.join(gpuusage)
print '<br>'
print 'total CPU usage: %.0f%%' % np.mean(cpuusage)
#print 'total memory usage: %.0f%%'% np.mean(memoryusage)
print '</font>'
print '<br>'
print '<br>'
print '</h3>'

print kbstopnodes
print '<br><br>'
print arenatopnodes
print '</font>'

print '<br><br>'

print "</html>"


